# Generated by Django 5.1.1 on 2024-10-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_user_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
